name: Terraform Plan (PR & Push)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tf-files/**'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - 'tf-files/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: tf-files
    concurrency:
      group: tf-plan-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init -input=false -no-color
      - run: terraform fmt -check
      - run: terraform validate
      # Exit code: 0=no changes, 2=changes present, 1=error
      - name: Terraform plan (detailed exit code)
        run: terraform plan -input=false -no-color -detailed-exitcode || test $? -eq 2
