name: Terraform Plan (PR & Push)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'tf-files/**'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - 'tf-files/**'
      - '.github/workflows/**'
  workflow_dispatch:

concurrency:
  group: terraform-plan-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    defaults:
      run:
        working-directory: tf-files

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: terraform init -input=false -no-color
      - run: terraform fmt -check
      - run: terraform validate

      # Exit code: 0=no changes, 2=changes, 1=error
      - name: Terraform plan (detailed exit code, waits for lock)
        id: plan
        shell: bash
        run: |
          set +e
          terraform plan -input=false -no-color -lock-timeout=5m -detailed-exitcode -out=tfplan.out
          code=$?
          echo "exit_code=$code" >> "$GITHUB_OUTPUT"
          if [ "$code" -eq 1 ]; then
            echo "Terraform plan failed"; exit 1
          fi
